### ISSUE TITLE
app link ?

### ISSUE THREAD

**Issue by aj07** [affinityproject/affinidi-core-sdk#32]
Hi, 

Is there any app link which I can clone and run it.  It feels like i have limited react knowledge.

I am trying to run through the docs.  While adding the components its giving error.

Thanks!

**Comment by launganik** [comment]
Hey @aj07, great timing for the question. We are working on open sourcing our internal playground. It's a react application that has a basic UI with some of the functionalities that our SDK offers. It's coming relatively soon. We'll announce it on https://twitter.com/affinidi. 

Meanwhile, out of curiosity, is there a specific use case you are targeting with Affinidi? I may be able to point you to some relevant VC schemas.

**Comment by aj07** [comment]
Hi, thanks for replying. 

I was working on some use case for a hackathon at the last moment. :)

**Comment by launganik** [comment]
Hello @aj07 we've just open sourced a playgroud react app https://github.com/affinityproject/affinidi-demo-browser-app

You can use app this to play around with some of the functionalities offered in the Affinidi SDK and eventually enable SSI for your own application.

Closing this issue for now. Feel free to reach out if you have any more questions!
